### ISSUE TITLE
Older macOS release unsupported

### ISSUE THREAD

**Issue by sbrkopac** [humbletim/install-vulkan-sdk#3]
Looks like there was a change on the macOS packaging from ```1.2.176.1``` onward. It used be archive-esque that could be extracted but in the more recent releases it looks like its an actual installer. This just effects macOS so probably not a huge deal but it would be nice to have support for older versions. You can validate this by running the workflow for version ```1.2.170.0``` or previous.

**Comment by humbletim** [comment]
Ahh, OK -- I was able to confirm just now that 1.2.170.0 breaks things. Taking a look at autodetecting the archive format so old versions can be supported.

**Comment by humbletim** [comment]
fixed in v1.1.1! (confirmed by running CI builds against _all available SDK versions_ as reported by LunarG webservices)

**Comment by sbrkopac** [comment]
This is so slick. Awesome awesome work.
