### ISSUE TITLE
Multiple deprecated actions that requires updates

### ISSUE THREAD

**Issue by spironan** [humbletim/install-vulkan-sdk#6]
First off, thank you for making such a tool. Exactly what i needed for my project who relies on VulkanSDK.

Using your current action is giving me warning (under annotations) informing Node.js and 'save-state' commands are deprecated and needs to be updated

I'm hoping to use this action for the foreseeable future so i hope it can be fixed to prevent any issues!

below are the following warnings

- Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/cache, actions/cache

- The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by humbletim** [comment]
thanks for the heads up!
